### ISSUE TITLE
:focusと:active疑似クラスが動いていない？

### ISSUE THREAD

**Issue by NowDeer** [otya128/web-bml#10]
CSSで、「p.text{}」「p:focus{border-top-color-index:1;・・・}」「p:active{border-top-color-index:・・・}」として、テキストのフォーカス位置がわかるようにした単純なBMLコンテンツなのですが、:focus,:active疑似クラスが動いていないようで、ボーダー色が変わってくれません。確認のほど、お願いいたします<(_ _)>

**Comment by otya128** [comment]
DOMのfocusStyleとactiveStyleの実装がそれなりに面倒そうでほとんど運用されていないため実装が後回しになっています

**Comment by NowDeer** [comment]
確かに、実運用ではPNGを使うので見ないですね。テストストリームなどの機能確認用のコンテンツでは、便利なのでよく使います。後回しで全然問題ありません。

**Comment by otya128** [comment]
READMEに乗せていたBS日テレで使われていることに気付いたのでfocusStyleとactiveStyle以外の部分を実装しました

**Comment by NowDeer** [comment]
ありがとうございます。無事、マイコンテンツのフォーカス位置がわかるようになりました。
