### ISSUE TITLE
MNGが止まらない

### ISSUE THREAD

**Issue by NowDeer** [otya128/web-bml#6]
MNGの実装、すばらしいです。ただ、streamStatusを「stop」にしても、MNGが止まって非表示にならず、表示されたままとなっております。モジュールロックで「play」にし、beeventのロック完了のタイミングで、「stop」にしているので、タイミングの問題かもしれません。ご確認いただけますと、ありがたいです。

**Comment by otya128** [comment]
未実装だったMNGのstreamStatusと未テストですがstreamPositionを実装しました。

**Comment by NowDeer** [comment]
無事動きました。ありがとうございますm(__)m
