### ISSUE TITLE
スクリプトでcharCodeAt()を使っているコンテンツ

### ISSUE THREAD

**Issue by NowDeer** [otya128/web-bml#8]
改行計算をスクリプトで行うためString.charCodeAt()を使って、2byte（全角）、1byte（半角）計算をしている場合、「改行が正常に行われない」という問題が発生しています。
「×」（全角）の場合、EUCコードでは、0xA1DFですが、Unicodeでは、0xD7となり、1byte（半角）と計算されてしまいます。
何か良い対応方法は、ありますでしょうか？

**Comment by otya128** [comment]
String.charCodeAtはEUC-JPの値が返るようにはなっているんですが、0x100未満であればかつて必要だったwindow.btoa, window.atobとの相互運用のためにそのまま返していました。この処理の必要性は 82a15923d629139125f60f54f69d1c1a3931acf8 で消滅したので削除しました。

**Comment by NowDeer** [comment]
無事、改行が正しく行われていました。ありがとうございますm(__)m
