### ISSUE TITLE
映像が止まってしまいます

### ISSUE THREAD

**Issue by NowDeer** [otya128/web-bml#9]
Windowsの環境で試しているのですが、映像が止まって、グルグル回る表示に開始から数分後になります。
調べていくと、ffmpegの標準エラー出力でパイプが詰まって止まるようです。
ffmpegのオプションで「-v quiet」をつけると、発生しなくなったのですが、確認いただきたく、よろしくお願いします。

**Comment by otya128** [comment]
FFMPEG_OUTPUT=1で検証していたので原因に気付きませんでした、ありがとうございます。

**Comment by NowDeer** [comment]
問題ないようです。ありがとうございました。
